### ISSUE TITLE
Double quote string not properly highlighted

### ISSUE THREAD

**Issue by LeChatP** [omBratteng/vscode-nftables#130]
If you write by example : 
```nft
iifname "net0" oifname "net1" drop
```
`net0" oifname "net1` is considered as simple string and not highlighted correctly

That's a detail, but, I think it's a regex pattern to change with `[^"]+`

Thank you for your awesome module ! Have a nice day !

**Comment by omBratteng** [comment]
@LeChatP feel free to open a PR if you think the regex change will work.
And screenshots would be nice.
I don't use nftables that much anymore, but still maintain the extension.

**Comment by andreas51** [comment]
I think the root cause of this issue is that _string.quoted.double_ is allowed as a part of the _string_ definition. This causes syntax highlighting for strings to not stop at the second double quote. Hence, _string_ syntax highlighting is broken for every line that has more than one double quoted element. Removing _string.quoted.double_ from the _string_ definition solves the problem and causes no issues within my netfilter test rules.

Am I missing some usecase where double quoted strings inside strings actually make sense and are required? If not, the suggested solution is in PR #194.
